services:
  - type: web
    name: telegram-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python telegram_bot.py"
    autoDeploy: true
    pythonVersion: "3.12"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: SERVICE_ACCOUNT_JSON
        sync: false

